import React from 'react';

export default function Home() {
    return (
        <main className="Home">
            HOME CONTENT HOME CONTENT HOME CONTENT HOME CONTENT HOME CONTENT HOME CONTENT HOME CONTENT HOME CONTENT HOME CONTENT HOME CONTENT HOME CONTENT HOME CONTENT HOME CONTENT HOME CONTENT HOME CONTENT HOME CONTENT HOME CONTENT HOME CONTENT
        </main>
    )
}
